# config/services.yaml

parameters:
  profile_photos_directory: "/public/uploads/profile_photos"
  profile_photos_web_path: "/uploads/profile_photos"
  property_photos_directory: '/public/uploads/property_photos'
  property_photos_web_path: '/uploads/property_photos'
  frontend_upload_directory: '../../FRONT/public/uploads/property_photos'
  stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'



services:
    App\EventSubscriber\MailLoggerSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }
    # default configuration for services in *this* file
    App\EventListener\DemandeReservationListener:
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
        App\Utils\ReservationNumberGenerator:
        public: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
