nelmio_cors:
    defaults:
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_credentials: false
        allow_headers: ['content-type']
        allow_methods: ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/': 
            allow_origin: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
