easy_admin:
    entities:
        Prestataire:
            class: App\Entity\Prestataire
            label: 'Prestataires'
            list:
                fields:
                    - id
                    - type
                    - tarif
                    - verified
                    - { property: 'user', type: 'association', label: 'User' }
            form:
                fields:
                    - type
                    - tarif
                    - verified
                    - { property: 'user', type: 'association', label: 'User' }

        Property:
            class: App\Entity\Property
            label: 'Properties'
            list:
                fields:
                    - { property: 'id', label: 'ID' }
                    - { property: 'name', label: 'Name' }
                    - { property: 'description', label: 'Description' }
                    - { property: 'price', label: 'Price' }
                    - { property: 'category', label: 'Category' }
                    - { property: 'proprio', label: 'Owner' }
                    - { property: 'createdAt', label: 'Created At', type: 'datetime' }
                    - { property: 'image', label: 'Image', template: '@EasyAdmin/default/field_image.html.twig', base_path: '/uploads/property_photos' }
            form:
                fields:
                    - { property: 'name', label: 'Name' }
                    - { property: 'description', label: 'Description' }
                    - { property: 'price', label: 'Price' }
                    - { property: 'category', label: 'Category' }
                    - { property: 'proprio', label: 'Owner' }
                    - { property: 'image', label: 'Image', type: 'vich_image' }
                    - { property: 'createdAt', label: 'Created At', type: 'datetime' }
